/// Common nationalities for walk-in guest demographics.
abstract final class GuestNationalities {
  static const List<String> all = [
    'Filipino',
    'American',
    'Australian',
    'British',
    'Canadian',
    'Chinese',
    'French',
    'German',
    'Indian',
    'Indonesian',
    'Italian',
    'Japanese',
    'Korean',
    'Malaysian',
    'Mexican',
    'Dutch',
    'New Zealander',
    'Norwegian',
    'Portuguese',
    'Russian',
    'Saudi Arabian',
    'Singaporean',
    'South African',
    'Spanish',
    'Swedish',
    'Swiss',
    'Taiwanese',
    'Thai',
    'Turkish',
    'Ukrainian',
    'Vietnamese',
    'Other',
  ];
}
